name: 'Build (Stable)'

on:
  workflow_dispatch:

jobs:
  
  build:

    runs-on: [self-hosted, linux, x64]

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Update Pip and install requirements
        run: |
           pip install -U pip
           pip install -r requirements.txt
           pip install -U nuitka

      - name: Install compilers
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu zip

      - name: Build for Linux ARM64
        run: |
          CC=aarch64-linux-gnu-gcc nuitka --onefile --standalone main.py
          cd build
          mv main.bin onedisc
          zip -r "/tmp/OneDisc-Linux-ARM64.zip" ./onedisc

