name: 'Build (Dev)'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  get-version-number:
    runs-on: ubuntu-latest    
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: "Get version number"
        id: get_version
        run: |
          export VERSION=$(python -c 'print(__import__("version").VERSION)')
          export SUB_VER=$(git rev-list --no-merges --count $(git describe --tags --abbrev=0)..HEAD)
          echo "Currect Version Number: $VERSION.$SUB_VER"
          echo "SUB_VER = $SUB_VER" >> version.py
          echo "::set-output name=VERSION::$VERSION.$SUB_VER.0"
          echo "::set-output name=SUB_VER::$SUB_VER"
    
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      sub_ver: ${{ steps.get_version.outputs.SUB_VER }}

  build:
    needs: get-version-number
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86, x64, arm64]
    steps:

      - name: "Checkout"
        uses: actions/checkout@v3
      
      - name: "Setup Python"
        uses: actions/setup-python@v3
        with:
          python-version: 3.11  # 保证兼容性

      - name: "Install requirements"
        run: |
          python -m pip install --upgrade pip
          pip install -r -U requirements.txt
          pip install -r -U nuitka
      
      - name: "Write version number (Windows)"
        if: matrix.os == 'windows-latest'
        run: |
          Add-Content -Path "version.py" -Value "SUB_VER = `$env:SUB_VER"
        env:
          SUB_VER: ${{ needs.get-version-number.outputs.sub_ver }}
        
      - name: "Write version number"
        if: matrix.os != 'windows-latest'
        run: |
          echo "SUB_VER = $SUB_VER" >> version.py
        env:
          SUB_VER: ${{ needs.get-version-number.outputs.sub_ver }}
          
      - name: "Build executeable"
        run: |
          python -m nuitka\
            --onefile\
            --standalone\
            --follow-imports\
            --show-modules\
            --output-dir=build\
            --lto=yes\
            --windows-icon-from-ico=icon.ico\
            --windows-file-version=$env:VERSION\
            --windows-product-version=$env:VERSION\
            --windows-version-string=$env:VERSION\
            main.py
        env:
          VERSION: ${{ needs.get-version-number.outputs.version }}

      - name: "Upload build"
        uses: actions/upload-artifact@v3
        with:
          name: OneDisc for ${{ matrix.os }}-${{ matrix.arch }}
          path: build/*