name: 'Build (Dev)'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  
  build:

    runs-on: [self-hosted, linux, x64]

    steps:

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Update Pip and Install Requirements
        run: |
          pip install -U pip
          pip install -r requirements.txt
          pip install pyinstaller
          sudo apt install binutils -y



      - name: Build on Linux
        run: |
          pyinstaller --onefile --add-data "discord_cert.pem:." main.py
      
      - name: Get version number
        run: |
          export VERSION=$(python -c 'print(__import__("version").VERSION)')
          export SUB_VER=$(git rev-list --no-merges --count $(git describe --tags --abbrev=0)..HEAD)
          echo "VERSION=$VERSION.$SUB_VER" >> $GITHUB_ENV
          echo "Currect Version Number: $VERSION.$SUB_VER"

      - name: Compress file
        run: |
          sudo apt update
          sudo apt install zip git -y
          cd dist
          mv main onedisc
          zip -r "/tmp/OneDisc-linux-x86_64-dev.zip" onedisc


      - name: Publish document
        run: |
          cd /tmp
          rm -rf OneDisc-Homepage

          git clone https://github.com/ITCraftDevelopmentTeam/OneDisc-Homepage.git
          cd OneDisc-Homepage
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/ITCraftDevelopmentTeam/OneDisc-Homepage.git
  
          cd /tmp/OneDisc-Homepage/docs/public
          mkdir downloads --parents
          cd downloads
          mv /tmp/OneDisc-linux-x86_64-dev.zip .
          cd /tmp/OneDisc-Homepage/docs

          sed -i "s/<!--ver2--><!--ver2.end-->/<!--ver2-->\`$VERSION\`<!--ver2.end-->/g" download.md

          git add -A
          git config --global user.name "github-actions[bot]"
          git config --global user.email "action@github.com"
          git commit -m "Update version to $VERSION"
          git push
        env:
          VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ secrets.GH_TOKEN_1 }}

